name: Build Gosh

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.3'

      - name: Install dependencies
        run: |
          go mod download

      - name: Run build
        run: go build .

      - name: Run vetting/linting
        run: |
          go vet -json -c=3 . > vet-results.json

      - name: Upload Vet report
        uses: actions/upload-artifact@v2
        with:
          name: Vetting results
          path: vet-results.json

      - name: Run testing
        run: go test -json ./... > test-results.json

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: Test results
          path: test-results.json